### ISSUE TITLE
Missing symbolic hardware ID for 0x3

### ISSUE THREAD

**Issue by dbrignoli** [audioscience/u-boot-omap3#10]
Hi @sgturner, this file https://github.com/audioscience/u-boot-omap3/blob/asi1230-master/board/asi1230/hwids.h has #defines for H/W IDs but is missing one for 0x3. What should the #define string for 0x3 be? ```B_HWID_ASI??????```. Thank you

**Comment by sgturner** [comment]
The schematic says:
```
000 = ASI2610: 32-bit 200MHz DDR2 + 300MHz ARM+DSP
001 = ASI1230: 32-bit 200MHz LPDDR
010 = ASI2620, ASI67xx, 32bit 400MHz DDR2 + 720/600MHz ARM/DSP, GPMC
011 = ASI67xx, 16bit 400MHz DDR2 + 720/600MHz ARM/DSP, GPMC
```

so I'd change the defines to be:
```
#define B_HWID_ASI2610 0x0
#define B_HWID_ASI1230 0x1
#define B_HWID_ASI2620_ASI6700_32BIT 0x2
#define B_HWID_ASI2620_ASI6700_16BIT 0x3
```

**Comment by dbrignoli** [comment]
```#define B_HWID_ASI2620_ASI6700_16BIT 0x3```
0x3 implies 64 Mbytes of external memory. That's not enough memory for Hono AVB Devices. So the ID should be ```#define B_HWID_ASI6700_16BIT 0x3```.

**Comment by sgturner** [comment]
Yes, I agree and I have changed the schematic as well

**Comment by dbrignoli** [comment]
Done, see 14e670da37e7b34fff65fee298d2e3b8264771a4
