### ISSUE TITLE
Tag, test and release a new asi6700 boot loader (v12)

### ISSUE THREAD

**Issue by dbrignoli** [audioscience/u-boot-omap3#11]
While working on https://github.com/audioscience/drv/issues/414 I made some changes to improve recovery from warm-reset. Should be tag, test and release?

FYI: changes were tested locally by me and they work on my test PC.

**Comment by sgturner** [comment]
This is boot-loader v12 (?).  Need to test with unload/re-load, and warm reset.

**Comment by dbrignoli** [comment]
Zipped v12 image attached

[u-boot.pcie.spi_v12.zip](https://github.com/audioscience/u-boot-omap3/files/2488389/u-boot.pcie.spi_v12.zip)

**Comment by andrew-elder** [comment]
Who is testing it?

**Comment by dbrignoli** [comment]
> Who is testing it?

This is currently in @sgturner's court.

**Comment by sgturner** [comment]
I have this running on an ASI5811 and have tested on 1 computer so far.  Ther eare three tests:
1. Unload/load DSP code from Windows (I've used the python script to loop)
2. Warm boot (Restart)
3 Cold boot (Power cycle)
Which one should I concentrate on?

**Comment by sgturner** [comment]
I guess I should have read the beginning of the issue - warm boot

**Comment by sgturner** [comment]
I did 5 Restarts with no issues

**Comment by dbrignoli** [comment]
We are interested in testing all of them: driver unload/load, cold boot, warm boot, hard reset

All of the above with drivers < 4.20.16 and > 4.20.16

**Comment by sgturner** [comment]
I'm not seeing my python load/unload script run for more than 10 minutes or so without failing.  The script is not reporting any errors, but Windows reports that the "Device was not loaded" and the LEDs seem to be stuck at D1 and D2 lit.

I'm running:
```
import os
import socket, sys
import platform
import subprocess
import time
from audioscience.driver import unload_load


    
def main():
    count = 0
    while True:
        count=count+1
        print "Iteration %d" % count
        unload_load.unload_load_asi_devices()
        
main()
```

and am getting:
```
.
Iteration 2210
Unload all ASI devices
PCI\VEN_104C&DEV_B801&SUBSYS_6780175C&REV_00\4&51E1C08&0&00E0: Removed
Scan and wait till all ASI devices found
. .
PCI\VEN_104C&DEV_B801&SUBSYS_6780175C&REV_00\4&51E1C08&0&00E0: AudioScience ASI5700/5800/6700 - HPI
Check that each device is running OK
.
Iteration 2211
Unload all ASI devices
PCI\VEN_104C&DEV_B801&SUBSYS_6780175C&REV_00\4&51E1C08&0&00E0: Removed
Scan and wait till all ASI devices found
. .
PCI\VEN_104C&DEV_B801&SUBSYS_6780175C&REV_00\4&51E1C08&0&00E0: AudioScience ASI5700/5800/6700 - HPI
Check that each device is running OK
.
Iteration 2212
Unload all ASI devices
PCI\VEN_104C&DEV_B801&SUBSYS_6780175C&REV_00\4&51E1C08&0&00E0: Removed
Scan and wait till all ASI devices found
. .
PCI\VEN_104C&DEV_B801&SUBSYS_6780175C&REV_00\4&51E1C08&0&00E0: AudioScience ASI5700/5800/6700 - HPI
Check that each device is running OK
.
```

**Comment by dbrignoli** [comment]
Driver version? Does the same thing happen with the release boot loader?

**Comment by sgturner** [comment]
OK, with a different ASI5800 and u-boot v11, my load/unload script does eventually fail:


>>>Iteration 5182
LOAD
Scan and wait till all ASI devices found
. .
PCI\VEN_104C&DEV_B801&SUBSYS_6780175C&REV_00\4&51E1C08&0&00E0: AudioScience ASI5700/5800/6700 - HPI
Check that each device is running OK
```
LIST
Scan for ASI devices
PCI\VEN_104C&DEV_B801&SUBSYS_6780175C&REV_00\4&51E1C08&0&00E0: AudioScience ASI5700/5800/6700 - HPI
UNLOAD
Unload all ASI devices
PCI\VEN_104C&DEV_B801&SUBSYS_6780175C&REV_00\4&51E1C08&0&00E0: Removed on reboot
Not all of 1 device(s) removed, at least one requires reboot to complete the operation.
```

**Comment by sgturner** [comment]
Looks like we need a new issue?

**Comment by dbrignoli** [comment]
> Looks like we need a new issue?

Yep, I think so.

**Comment by sgturner** [comment]
Need to reboot PC continuously,

Need an app to:

- auto start
- verify adapter is running using HPI
- reboot PC

Write in python.

**Comment by sgturner** [comment]
@asitom will implement

**Comment by asitom** [comment]
@sgturner - added apps\python\audioscience\driver\reboottest.py

1. Install it in the same directory as unload_load.py and the devcon app.
2. Create a shortcut to it in the windows startup directory (C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp)
3. Run it.

It will create a text file on the desktop with count of reboots and count of failures.

**Comment by andrew-elder** [comment]
Actually, SteveT should stay out of the testing. We should run tests here in NY. Steve has enough stuff to do right now.

**Comment by andrew-elder** [comment]
Baseline test run last night with v11. Reboot test script reports 584 successful reboots and 0 failures.

**Comment by sgturner** [comment]
Thats good (I guess).  What model of card and rev?

**Comment by andrew-elder** [comment]
I'm having trouble programming.
This
```
>\python27\python asi1230serialutil_asi6700_v11.pyz bootstrap_6700 --serial-dev \\.\COM4
```
works. But this
```
C:\asi\sw\utility>\python27\python asi1230serialutil bootstrap_6700 --serial-dev \\.\COM4 --spi-img u-bootv12.bin
```
gives
```
No boot image specified and internal image not present. exiting.
```
Note that u-bootv12.bin is a renamed version of u-boot.pcie.spi_v12 from u-boot.pcie.spi_v12.zip that is attached further up this issue.

**Comment by andrew-elder** [comment]
This worked
```
C:\asi\sw\utility>\python27\python asi1230serialutil_asi6700_v11.pyz bootstrap_6700 --serial-dev \\.\COM4 --spi-img u-bootv12.bin
```

**Comment by dbrignoli** [comment]
Yes, that's because two images are needed. You provided one but the other (the one that does serial booting of the card) is bundled with the .pyz file.

**Comment by andrew-elder** [comment]
Ok, test is running.....

**Comment by andrew-elder** [comment]
Ran v12 overnight. 662 successful reboot cycles and no failures. I think we are ok to release this one.

**Comment by sgturner** [comment]
Can we also try V1 and V2 with ASI6700 revF? (different PCIe reset circuitry)

**Comment by sgturner** [comment]
V11 and V12

**Comment by andrew-elder** [comment]
Will do that today.

**Comment by andrew-elder** [comment]
@sgturner - Actually, we only have revD. No revF. Will revD do to test this?

**Comment by sgturner** [comment]
Yes, same PCIe reset mechanism

**Comment by andrew-elder** [comment]
Oops. Didn't get this test started until today. Now running v12 on a ASI6788 revD0.

**Comment by andrew-elder** [comment]
v12 on ASI6788 revD0 ran ok over the weekend. 2323 successful reboots were recorded and zero errors.

**Comment by andrew-elder** [comment]
@sgturner - what is the next step with this issue?

**Comment by sgturner** [comment]
If everybody is happy with it then we can start using in production.

Like the driver, we probably need a TWiki sign-off page, where we test it on a 67xx, 679x, 58xx on several computers in NY and CA.  The test just makes sure it boots

CA: Henry's test machine.  ASI58xx, 67xx and 679x
NY: some test machine:  ASI58xx, 67xx and 679x

-steve

**Comment by andrew-elder** [comment]
Good idea. I'll create the page.

**Comment by sgturner** [comment]
@andrew-elder has already created the page:

https://secure.sourcehosting.net/AudioScience/twiki/bin/view/Main/BootloaderReleaseSignoff6700

Can I have the official v12 .pyz to be on DropBox in firmware

**Comment by dbrignoli** [comment]
I’ll package it up and upload it

**Comment by andrew-elder** [comment]
Please ping me when it is there and I'll have SteveP test out a few cards and machine here.

**Comment by dbrignoli** [comment]
> Please ping me when it is there and I'll have SteveP test out a few cards and machine here.

Hi @andrew-elder, v12 .pyz uploaded to `engineering/firmware/5800_6700`. I uncompressed the production v11 .pyz currently in use and I found it contained a few copies of earlier version of itself, earlier bootloader images and some other stray files that happened to be in the checkout directory at the time the .pyz was created. (Reminded me of Katamari Damacy https://en.wikipedia.org/wiki/Katamari_Damacy#Gameplay)

**Comment by andrew-elder** [comment]
@dbrignoli - v12 didn't boot in any systems here. I'll revert to v11 and see if that works. I assume you tested it?

**Comment by dbrignoli** [comment]
> I assume you tested it?

I did test the bootloader image when I first attached to this issue. The rest of the issue was about getting third party testing/confirmation that it worked so when I got the green light I packaged the image I originally attached to this issue (see 
https://github.com/audioscience/u-boot-omap3/issues/11#issuecomment-430702354).

Which u-boot.bin did you use for testing?

**Comment by andrew-elder** [comment]
The one referenced here https://github.com/audioscience/u-boot-omap3/issues/11#issuecomment-469834915

**Comment by andrew-elder** [comment]
Well, drat. This is my bad. It works. Once I pulled it apart again, I noticed I left the programming jumper in place....

**Comment by dbrignoli** [comment]
All good then? 😃

**Comment by andrew-elder** [comment]
NY has done it's testing. No issues.

**Comment by sgturner** [comment]
tested with v12 PYZ file on a 5788 revF6 and 6788 G0.  works fine.  Will instruct Henry to start using in production

**Comment by sgturner** [comment]
tested with v12 PYZ file on a 5788 revF6 and 6788 G0.  works fine.  Will instruct Henry to start using in production
